server:
  port: 8080

spring:
  rabbitmq:
    host: 192.168.17.230
    port: 5672
    username: user_test
    password: user_test
    virtual-host: manufacture
    template:
      retry:
        enabled: true
        initial-interval: 1s

file:
  upload:
    config:
      imageUrl: http://47.96.77.229:9300/file/upload?action=upload
      imagePath:
      imageFieldName: file
      imageMaxSize: 10485760
      imageAllowFiles:
        - .png
        - .jpg
        - .jpeg
        - .gif
        - .bmp